# Site settings
title: Mysterious Pants
author: Mysterious Pants
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://mysteriouspants.com"
twitter_username: mysterytrousers
github_username:  mysteriouspants

paginate: 5
paginate_path: /:num

exclude: [ README.md, COPYING.md ]
timezone: America/Los_Angeles
encoding: utf-8

# Build settings
markdown: kramdown
ink_watch: theme
