name: Mysterious Pants
description: It's an adventure, 314!
meta_description: "Mysterious Pants, it's an adventure, 314!"

aboutPage: false

markdown: kramdown
highlighter: rouge

paginate: 5
gems: [ jekyll-paginate ]
paginate_path: /:num

baseurl: /
domain_name: 'http://mysteriouspants.com'

disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://mysteriouspants.com'
author:         'Mysterious Pants'
authorTwitter:  'mysterytrousers'

permalink:       /:year/:month/:day/:title/

exclude: [ README.md, COPYING.md ]
timezone: America/Los_Angeles
encoding: utf-8

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
